[build]
  publish = "frontend"
  command = "echo 'No build required for static site'"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.render.com/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
